### ISSUE TITLE
Would be great to have more manuals on using

### ISSUE THREAD

**Issue by ponyatov** [revng/llvmcpy#30]
I'm looking LLVM bindings for Python 3, and most of them look obsolete, does not have manuals, provides only C API, or something like that.

For me now C API is enough for start, but I need cross-compiler backend (MIPS or ARM), is `llvmcpy` suitable?

The rich manual is not required may be, but here it will be great to have a lot of links to project source code with uses `llvmcpy` as a sample.

**Comment by aleclearmind** [comment]
`llvmcpy` is a wrapper around the C API, which allows you to do many things.

If the [LLVM-C API](https://llvm.org/doxygen/group__LLVMC.html) can do something, we can too.

You can find examples in [test.py](https://github.com/revng/llvmcpy/blob/master/llvmcpy/test.py) or in [revng/docs/instrument.py](https://github.com/revng/revng/blob/develop/docs/instrument.py).

Hope this helps.

This said, this issue is too vague, closing it. Feel free to write me privately.
